title: Your awesome title
author: Stephen Hathaway
email: hello@stphnhthwy.com
description: Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description. I have added shit to this.

sass:
    style: compact

# Build settings
theme: smpl
